site_name: Opti
site_url: https://basf.github.io/mopti
repo_name: basf/mopti
repo_url: https://github.com/basf/mopti

nav:
  - index.md
  - Install: install.md
  - Getting started: problem.md
  - Examples:
    - examples/problem_reduction.md
  - Datasets:
    - datasets/alkox.md
    - datasets/benzylation.md
    - datasets/cake.md
    - datasets/fullerenes.md
    - datasets/hplc.md
    - datasets/photodegradation.md
    - datasets/snar.md
    - datasets/suzuki.md
    - datasets/reizmann-suzuki.md
    - datasets/baumgartner-aniline.md
    - datasets/baumgartner-benzamide.md
  - API Reference:
    - Problem: ref-problem.md
    - Parameter: ref-parameter.md
    - Objective: ref-objective.md
    - Constraint: ref-constraint.md
    - Model: ref-model.md
    - Metric: ref-metric.md
    - Sampling: ref-sampling.md
    - Tools: ref-tools.md
    - Test Problems: ref-problems.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - toc.integrate

plugins:
  - search
  # https://mkdocstrings.github.io/
  - mkdocstrings:
      watch:  # watch for changes when serving locally
        - opti
      # handlers:
      #   python:
      #     rendering:
      #       show_root_heading: yes
      #       show_root_full_path: no

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/math/?h=math#mathjax
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition

extra_css:
  - stylesheets/style.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js